### ISSUE TITLE
Переписать title и description в коде

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/Marketing#27]

**Comment by solodikov** [comment]
Нужен Фронт.

**Comment by solodikov** [comment]
Павел, как будешь на этой задаче - телеграфируй, дам формулировки и созвонимся кое-что поясню.

**Comment by solodikov** [comment]
@pavelit, сейчас Title:
Голос

Нужно прописать:
**GOLOS.io Блоги**

Причём, нужно сделать так, чтобы он отображался при оформлении постов по OG не так как сейчас через тире:
**Какое-то название поста - Голос**

А с вертикальной линией (с пайплайн):
**Какое-то название поста | GOLOS.io Блоги**
