### ISSUE TITLE
Привязать G+ и ОК через саппорт Novapress

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/Marketing#29]

**Comment by solodikov** [comment]
G+ привязали.
OK - пока никак, делаем запрос в саппорт ОК.

**Comment by solodikov** [comment]
Не понятно, почему именно, но ОК к Новапресс не привязывается, а саппорт ОК тормозной.
Всё работает, но нет Однокласнников, в него пока постим через Амплифер.
Задачу закрываю.
