### ISSUE TITLE
Создать и разместить мета теги Og Meta Properties

### ISSUE THREAD

**Issue by solodikov** [GolosChain/Marketing#7]
Бесплатный генератор: http://seowarlock.ru/webmaster/generator-og-properties.php

**Comment by serejandmyself** [comment]
Разве это не оно:

https://github.com/GolosChain/tolstoy/blob/master/app/utils/ExtractMeta.js

https://github.com/GolosChain/tolstoy/blob/master/config/client_config.js

@Undeadlol1 ?

Если так, то закрываем, если там что то не верно, то тогда вопрос к тебе @solodikov
