### ISSUE TITLE
Переделать страницу /ico#team

### ISSUE THREAD

**Issue by solodikov** [GolosChain/Marketing#9]
Переделать страницу /ico#team согласно обговорённому ранее с Костей и Сергеем:

- киберфонд убираем
- в команде пока пишем нас четверых (+ фулл, как будет)
- добавляем делегатов в меню
- составляем список делегатов с фото, возможно настраиваем и подтягиваем авто-обновление этого списка

**Comment by serejandmyself** [comment]
Not important - backlog issue
